---
- set_fact:
    apt_packages: "{{ __apt_packages|list }}"
  when: apt_packages|default(None) == None

- name: Cleanup role default variables
  set_fact:
    __apt_packages: !!null

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-container-systemd"
     package_depends: "{{ apt_packages }}"

# Ansible's systemd module fails with Packer's docker builder:
#  "System has not been booted with systemd as init system (PID 1). Can't operate.
#   Failed to connect to bus: Host is down"

- include_role:
    name: jm1.systemd
  vars:
    name: item
    masked: yes
  loop:
  - keyboard-setup.service
  - system-getty.slice
  - console-setup.service

# NOTE: systemd-tmpfiles-setup.service is required e.g. for creation of /run/screen directory
# TODO: Mask systemd-remount-fs.service systemd-update-utmp.service systemd-sysusers.service, too?

# mask services that do not make sense in containers
- include_role:
    name: jm1.systemd
  vars:
    name: item
    masked: yes
  loop:
  - NetworkManager.service
  - ModemManager.service
  - avahi-daemon.socket
  - avahi-daemon.service
  - wpa_supplicant.service
  - udisks2.service
  - upower.service

- copy:
    src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/"
    dest: /
    mode: preserve

- include_role:
    name: jm1.systemd
  vars:
    name: prepare-container.service
    enabled: yes

- set_fact:
    apt_packages: !!null
